runtime: python310  # using Python 3.10
instance_class: F2  # F2 instance

entrypoint: gunicorn -b :$PORT app:app  # points to the Flask instance in your app.py

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 15
